[package]
name = "rifs"
version = "4.12.0"
edition = "2021"
license = "MIT"
description = "Rust as your Flutter backend, Flutter as your Rust frontend"
repository = "https://github.com/cunarist/rinf"
